gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    cookie:
        enabled: true
        same_site: none               # default value
        path: /                      # default value
        domain: null                 # default value
        http_only: true              # default value
        secure: true                 # default value
        partitioned: false           # default value
        remove_token_from_body: true # default value
