lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600
    token_extractors:
        authorization_header:
            enabled: false # Désactiver l'extraction par en-tête Authorization
        cookie:
            enabled: true # Activer l'extraction par cookie
            name: access_token # Nom du cookie contenant le token