nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link', 'Authorization' ]
        max_age: 3600
        allow_credentials: true  # Ajout de cette ligne pour autoriser les credentials
    paths:
        '^/nsit-api/': # Assurez-vous que ce chemin est correct pour ton API
            allow_origin: [ '*' ]
            allow_methods: [ 'GET', 'POST', 'OPTIONS' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
            expose_headers: [ 'Link', 'Authorization' ]
            allow_credentials: true
