# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    timezone: '%env(APP_TIMEZONE)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Azure OAuth Service declaration
    #This service must have 3 arguments: clientId, clientSecret & redirectUri
    #These arguments are defined in .env.dev & .env.prod

    App\Security\Hasher\Sha256PasswordHasher:
        tags:
            - { name: security.user_password_hasher, alias: sha256 }
    #Service pour authentification custom
    App\Security\CustomAuthenticator:
        arguments:
            $userProvider: '@security.user.provider.concrete.user_provider'
            $passwordEncoder: '@security.password_hasher'

    #Service pour gérer l'expiration des token dans les cookies etc
    App\EventSubscriber\RemoveExpiredTokenSubscriber:
        arguments:
            $jwtManager: '@lexik_jwt_authentication.jwt_manager'
            $entityManager: '@doctrine.orm.entity_manager'
        tags:
            - { name: 'kernel.event_subscriber' }


    lcobucci.jwt.decoder:
        class: lcobucci\JWT\Decoder\Decoder
        public: true

#    App\Controller\Auth\Services\AzureOAuthService:
#        public: true
#        arguments:
#            $azureClientId: '%env(AZURE_OAUTH_CLIENT_ID)%'
#            $azureClientSecret: '%env(AZURE_OAUTH_CLIENT_SECRET)%'
#            $azureRedirectUri: '%env(AZURE_REDIRECT_URI)%'